on:
  push:
    branches: ['main', 'ci']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Determine image tags
        id: determine-tags
        run: |
          tags=()
          case "$GITHUB_REF_NAME" in
            main | master )
              tags+=(latest)
              ;;
          esac
          tags+=("$GITHUB_REF_NAME")
          readarray -t -O ${#tags[@]} tags < \
            <(git tag --points-at "$GITHUB_SHA" \
                      --format '%(refname:lstrip=-1)' |
              grep -E '^v[0-9]' |
              sed -r 's/^v//')
          echo "Image tags: ${tags[@]}"
          echo IMAGE_TAGS="${tags[@]}" >>"$GITHUB_OUTPUT"

      - name: Build base container image
        id: build-base-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.determine-tags.outputs.IMAGE_TAGS }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          context: base
          containerfiles: |
            base/Containerfile

      - name: Build Python container image
        id: build-python-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}-python
          tags: ${{ steps.determine-tags.outputs.IMAGE_TAGS }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          context: python
          containerfiles: |
            python/Containerfile
          build-args: |
            base=${{ steps.build-base-image.outputs.image-with-tag }}

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push base image to GitHub container registry
        id: push-base-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-base-image.outputs.image }}
          tags: ${{ steps.build-base-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Push Python image to GitHub container registry
        id: push-python-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-python-image.outputs.image }}
          tags: ${{ steps.build-python-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
